### ISSUE TITLE
Error: The content of the hibernation file had been wiped out. (but it's not)

### ISSUE THREAD

**Issue by AddaxSoft** [comaeio/Hibr2Bin#3]
I'm a bit confused by this error message.

![image](https://cloud.githubusercontent.com/assets/6898938/23341946/47776528-fc51-11e6-9639-58f6985e5ce4.png)

when the `hiberfil.sys` is actually 3.6 gb and contains lot of data.
If I run `strings` on it I can still retrieve a lot of user data.

**Comment by msuiche** [comment]
Please try the official version from www.comae.io

**Comment by AddaxSoft** [comment]
I'm using the "_official_" version; I just compiled it from source since the binary is not out there :)

Anyways, I did download "the official" binary from your website and still same error in fact the compiled one seems to be more recent?

![image](https://cloud.githubusercontent.com/assets/6898938/23363236/f495a44c-fcf9-11e6-94cd-11ff22f80e63.png)

**Comment by AddaxSoft** [comment]
We investigated this issue more; according to https://www.504ensics.com/uploads/publications/modern-windows-hibernation.pdf modern windows will put a header magic `WAKE` in the hiberfil.sys but doesn't actually zero-out the file. (hence I see data).

In fact if I change `WAKE` to `HIBR` (the magic word for still hibernated) the program works:
![image](https://cloud.githubusercontent.com/assets/6898938/23379567/b5610382-fd37-11e6-827c-e85280baf420.png)


do you want to create a patch for this issue?
