### ISSUE TITLE
Where to download compiled version?

### ISSUE THREAD

**Issue by masardisaja** [comaeio/Hibr2Bin#5]
Hi there,

Where I can download the compiled version of Hibr2Bin? I can't open https://my.comae.io

Thank you

**Comment by gittestshay** [comment]
Hi, you can download it after registration at https://www.comae.com/, you will find it in the toolkit.

**Comment by masardisaja** [comment]
Thank you. Is it support Windows 10 x64 86363 hibernation file?

**Comment by gittestshay** [comment]
Hi, Do you mean build 18363 (version 1909)? I converted some hibernation files from this version lately and it seems working fine!

**Comment by masardisaja** [comment]
Yes it is.
I used /PLATFORM X64 /MAJOR 10 /MINOR 0 parameter. Is this correct?

**Comment by gittestshay** [comment]
Yes, These are the parameters to use :) .
